---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
require(GGally, quietly = TRUE)
require(reshape2, quietly = TRUE)
require(tidyverse, quietly = TRUE, warn.conflicts = FALSE)
library(ggfortify)
library(cluster)
library(ggdendro)
library(broom)
theme_set(theme_bw())
```

```{r}
data <- read_csv("data/detections.csv.gz") %>% na.omit()
data <- data %>% select(audio_source_id, track_id)
#data %>% ggpairs()
```
```{r}
summary(data)
```

```{r}
data_sample <- data[sample(nrow(data), 30000), ]

data.scaled <- data_sample %>%  mutate_each(funs(as.vector(scale(.))))
summary(data.scaled)
```


```{r}
dists <- data.scaled %>% 
    as.data.frame() %>% 
    dist(method = "euclidean")
hc = hclust(dists, method = "ward.D")

plot(hc, cex = .6)
plot(hc, hang = -1)
n_clusters = 10
rect.hclust(hc, k=n_clusters)
```

```{r}

data_sample <- data_sample %>% 
    mutate(cluster = hc %>% 
               cutree(k = n_clusters) %>% 
               as.character())

data.scaled <- data.scaled %>%
  mutate(cluster = hc %>% 
               cutree(k = n_clusters) %>% 
               as.character())

```

```{r}
km = data_sample %>% 
  select(audio_source_id, track_id) %>%
  kmeans(centers = n_clusters, nstart = 20)

agrupado = km %>% 
  augment(data_sample)

agrupado %>%
  ggplot(aes(audio_source_id,track_id, color = .cluster)) +
  geom_point(size = 2) + 
    scale_y_log10()
```





```{r}
data.sample.km.long = km %>% 
    augment(data_sample) %>% # Adiciona o resultado de km 
                            # aos dados originais dw2.scaled em 
                            # uma vari치vel chamada .cluster
    gather(key = "vari치vel", 
           value = "valor",
           -track_id, -cluster) # = move para long todas as 
                                            # vari치vies menos repository_language 
                                            # e .cluster

data.sample.km.long %>% 
    ggplot(aes(x = `vari치vel`, y = valor, group = track_id, colour = cluster)) + 
    #geom_point(alpha = 0.2) + 
    geom_line(alpha = .5) + 
    facet_wrap(~ cluster) 
```

