---
title: "Desafio Playax"
author: "Dandara Sousa"
output: html_notebook
---

```{r}
#install.packages("tidyverse")
#install.packages("factoextra")
#install.packages("ggplot")
library(tidyverse)
library(factoextra)
library(ggplot2)
library(cluster)
```

Informações sobre os dados:
* __created_at__: quando o dado foi detectado
* __audio_source_id__: o id da rádio
* __track_id__: o id da música

```{r}
data <- read.csv("data/detections.csv")
data_ <- read_csv("data/detections.csv.gz")
head(data)
data_sample <- data[sample(nrow(data), 20000), ] %>% na.omit()
head(data_sample, n = 15)

```

```{r}
data_sample %>%
  group_by(audio_source_id) %>%
  ggplot(aes(audio_source_id, track_id)) +
  geom_jitter(aes(color = audio_source_id))
```

```{r}
res.hc <- data_sample %>% 
  dist(method = "euclidean") %>%
  hclust(method = "ward.D2")
```
```{r}
set.seed(123)

```



```{r}
data_sample <- data_sample %>% select(audio_source_id, track_id)
data_sample < scale(data_sample)

res.dist <- get_dist(data_sample, stand = TRUE, method = "pearson")

fviz_dist(res.dist,
   gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

```{r}
fviz_nbclust(data_sample, kmeans, method = "gap_stat")
```

```{r}

km.res <- kmeans(data_sample, 3, nstart = 25)

fviz_cluster(km.res, data = data_sample,
             ellipse.type = "convex",
             palette = "jco",
             ggtheme = theme_minimal())

fviz_cluster(km.res, data_sample)

```

```{r}
res.km <- eclust(data_sample, "kmeans", nstart = 25)
fviz_silhouette(res.km)
```


```{r}
fviz_dend(res.hc, k = 3, # Cut in four groups
          cex = 0.5, # label size
          k_colors = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07"),
          color_labels_by_k = TRUE, # color labels by groups
          rect = TRUE # Add rectangle around groups
          )
```